backend:
  name: github
  branch: netlifycms
  repo: jimafisk/budget.boston.gov
  base_url: https://blooming-retreat-39213.herokuapp.com
publish_mode: editorial_workflow
media_folder: "_source/fy19_recommended/img"
collections:
  - name: "landing-pages"
    label: "Landing Pages"
    folder: "_source/fy19_recommended/md"
    create: true 
    slug: "{{ slug }}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "chapters"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "featured-analysis"
    label: "Featured Analysis"
    folder: "_source/fy19_recommended/md/featured_analysis"
    create: true 
    slug: "featured-analysis/{{ slug }}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "chapters"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - label: "Card"
        name: "card"
        widget: "object"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Link", name: "link", widget: "string"}
      - label: "Components"
        label_singular: "Component"
        name: "components"
        widget: "list"
        types:
          - label: "Breadcrumbs"
            name: "breadcrumbs"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Published", name: "published", widget: "string" }
              - label: "Links"
                label_singular: "link"
                name: "links"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
                  - { label: "Local URL", name: "local", widget: "boolean", default: false }
              - { label: "Current", name: "current", widget: "string" }
          - label: "Intro"
            name: "intro"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Short Description", name: "short_desc", widget: "string" }
              - { label: "Description", name: "description", widget: "markdown" }
              - { label: "Sidebar Menu", name: "sidebar_menu", widget: "boolean", default: false }
          - label: "Text Block"
            name: "text_block"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
              - { label: "Right Image", name: "right_image", widget: "image" }
          - label: "Spanning Image"
            name: "spanning_image"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "desc", widget: "string" }
              - label: "Link"
                name: "link"
                widget: "object"
                fields:
                  - { label: "Text", name: "text", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
              - { label: "Image Source", name: "src", widget: "image" }
              - { label: "Alternative Text", name: "alt", widget: "string" }
          - label: "Grid"
            name: "grid"
            widget: "object"
            fields:
              - { label: "Grid Title", name: "grid_title", widget: "string" }
              - label: "Card"
                name: "card"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Body", name: "body", widget: "string" }
                  - { label: "Image", name: "image", widget: "image" }
              - { label: "Body", name: "body", widget: "markdown" }
              - { label: "Right Image", name: "right_image", widget: "image" }
          - label: "2 Column Text"
            name: "text_col_2"
            widget: "object"
            fields:
              - { label: "Column 1", name: "col1", widget: "markdown" }
              - { label: "Column 2", name: "col2", widget: "markdown" }
          - label: "3 Column Text"
            name: "text_col_3"
            widget: "object"
            fields:
              - { label: "Column 1", name: "col1", widget: "markdown" }
              - { label: "Column 2", name: "col2", widget: "markdown" }
              - { label: "Column 3", name: "col3", widget: "markdown" }
      - {label: "Body", name: "body", widget: "markdown"}
